[package]
name = "cust_shell_one"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
sysinfo = "0.33.1"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }


[build-dependencies]
winresource = "0.1"

